### ISSUE TITLE
DBouputService migration

### ISSUE THREAD

**Issue by francescobrivio** [cms-AlCaDB/AlCaTools#28]
Original issue: https://github.com/cms-sw/cmssw/issues/28699

In https://github.com/cms-sw/cmssw/pull/35048 some methods in ` CondCore/DBOutputService` were changed to accept pointers instead of references.

All calls to the following methods should migrated before the old methods (that still accept references and were left in the code in order not to break the release) can be removed:
- writeForNextLumisection
- writeOne
- writeMany
- createNewIOV

The PR https://github.com/cms-sw/cmssw/pull/35556 then renames the new method

gDoc for the files: https://docs.google.com/spreadsheets/d/1DJ6u45mBXW0bfYcdNNzauIT9nlWlyyjWZhKPuOmpB7U/edit#gid=1265504621

To do list:
 - [x] Prepare a list of all packages to be migrated
 - [x] Migrate the packages
 - [x] BeamSpot
 - [x] SiPixel
 - [x] SiStrips
 - [x] TkAlignment 
 - [x] ECAL
 - [x] HCAL
 - [x] DT
 - [x] CSC
 - [x] RPC
 - [x] Geometry
 - [x] JetMet
 - [x] Btagging
 - [x] AlCa
 - [x] DB
 - [x] Remove old methods that still accept references

**Comment by yuanchao** [comment]
To check which packages are still using the deprecated call with pointers instead of reference. Here are those call to writeOne:
 - Alignment/CommonAlignmentAlgorithm/plugins/SiPixelLorentzAngleCalibration.cc
 - Alignment/CommonAlignmentAlgorithm/plugins/SiStripBackplaneCalibration.cc
 - Alignment/CommonAlignmentAlgorithm/plugins/SiStripLorentzAngleCalibration.cc
 - Alignment/CommonAlignmentAlgorithm/src/AlignmentParametersIO.cc
 - Alignment/CommonAlignmentAlgorithm/src/AlignmentParametersIORoot.cc
 - Alignment/CommonAlignmentAlgorithm/src/AlignmentUserVariablesIO.cc
 - Alignment/CommonAlignmentProducer/plugins/GlobalTrackerMuonAlignment.cc
 - Alignment/CommonAlignmentProducer/src/AlignmentProducerBase.cc
 - Alignment/HIPAlignmentAlgorithm/src/HIPUserVariablesIORoot.cc
 - Alignment/LaserAlignment/plugins/LaserAlignment.cc
 - Alignment/MillePedeAlignmentAlgorithm/src/MillePedeVariablesIORoot.cc
 - Alignment/MuonAlignment/plugins/MuonMisalignedProducer.cc
 - Alignment/MuonAlignment/src/MuonAlignment.cc
 - Alignment/OfflineValidation/plugins/TrackerGeometryCompare.cc
 - Alignment/SurveyAnalysis/plugins/SurveyDBUploader.cc
 - Alignment/SurveyAnalysis/plugins/SurveyInputTrackerFromDB.cc
 - Alignment/TrackerAlignment/plugins/CreateTrackerAlignmentRcds.cc
 - Alignment/TrackerAlignment/plugins/MCMisalignmentScaler.cc
 - Alignment/TrackerAlignment/plugins/MisalignedTrackerESProducer.cc
 - Alignment/TrackerAlignment/plugins/TrackerSystematicMisalignments.cc
 - Alignment/TrackerAlignment/src/TrackerAlignment.cc
 - CalibCalorimetry/EcalTrivialCondModules/src/EcalLaserCondTools.cc
 - CalibPPS/TimingCalibration/plugins/PPSDiamondSampicTimingCalibrationPCLHarvester.cc
 - CalibPPS/TimingCalibration/plugins/PPSTimingCalibrationPCLHarvester.cc
 - CalibTracker/SiPixelQuality/plugins/SiPixelStatusHarvester.cc
 - CalibTracker/SiStripChannelGain/src/SiStripGainsPCLHarvester.cc
 - CalibTracker/SiStripQuality/plugins/SiStripBadStripFromQualityDBWriter.cc
 - Calibration/EcalCalibAlgos/src/ECALpedestalPCLHarvester.cc
 - Calibration/LumiAlCaRecoProducers/plugins/CorrPCCProducer.cc
 - Calibration/TkAlCaRecoProducers/plugins/AlcaBeamSpotHarvester.cc
 - CommonTools/MVAUtils/plugins/GBRForestWriter.cc
 - CondCore/DBOutputService/test/stubs/IOVPayloadAnalyzer.cc
 - CondCore/DBOutputService/test/stubs/IOVPayloadEndOfJob.cc
 - CondCore/DBOutputService/test/stubs/MyDataAnalyzer.cc
 - CondCore/DBOutputService/test/stubs/Timestamp.cc
 - CondCore/DBOutputService/test/stubs/writeBlob.cc
 - CondCore/DBOutputService/test/stubs/writeBlobComplex.cc
 - CondCore/DBOutputService/test/stubs/writeInt.cc
 - CondCore/DBOutputService/test/stubs/writeKeyed.cc
 - CondCore/DBOutputService/test/stubs/writeMultipleRecords.cc
 - CondFormats/Common/test/ProduceDropBoxMetadata.cc
 - CondFormats/EcalObjects/test/stubs/EcalTimeBiasCorrectionsFillInitial.cc
 - CondFormats/MFObjects/test/MagFieldConfigDBWriter.cc
 - CondFormats/PCLConfig/plugins/AlignPCLThresholdsWriter.cc
 - CondFormats/PhysicsToolsObjects/test/TFormulaWriter.cc
 - CondFormats/PhysicsToolsObjects/test/TGraphWriter.cc
 - CondFormats/RecoMuonObjects/test/ProduceAgingObject.cc
 - CondFormats/SiPixelObjects/test/FastSiPixelFEDChannelContainerFromQuality.cc
 - CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerFromQualityConverter.cc
 - CondFormats/SiPixelObjects/test/SiPixelFEDChannelContainerWriteFromASCII.cc
 - CondFormats/SiPixelObjects/test/SiPixelQualityProbabilitiesTestWriter.cc
 - CondFormats/SiPixelObjects/test/SiPixelQualityProbabilitiesWriteFromASCII.cc
 - CondTools/CTPPS/plugins/PPSTimingCalibrationWriter.cc
 - CondTools/CTPPS/plugins/WriteCTPPSBeamParameters.cc
 - CondTools/CTPPS/plugins/WritePPSAlignmentConfig.cc
 - CondTools/CTPPS/plugins/WritePPSAlignmentConfiguration.cc
 - CondTools/CTPPS/plugins/WritePPSAssociationCuts.cc
 - CondTools/CTPPS/src/CTPPSRPAlignmentInfoAnalyzer.cc
 - CondTools/CTPPS/src/WriteCTPPSPixGainCalibrations.cc
 - CondTools/CTPPS/src/WriteCTPPSPixelAnalysisMask.cc
 - CondTools/CTPPS/src/WriteCTPPSPixelDAQMapping.cc
 - CondTools/DT/plugins/DTKeyedConfigDBInit.cc
 - CondTools/DT/src/DTKeyedConfigHandler.cc
 - CondTools/DT/src/DTUserKeyedConfigHandler.cc
 - CondTools/Ecal/plugins/EcalMustacheSCParametersMaker.cc
 - CondTools/Ecal/plugins/EcalSCDynamicDPhiParametersMaker.cc
 - CondTools/Ecal/src/EcalDBCopy.cc
 - CondTools/Ecal/src/EcalLaser_weekly_Handler.cc
 - CondTools/Geometry/plugins/PPSGeometryBuilder.cc
 - CondTools/Hcal/plugins/BufferedBoostIODBWriter.cc
 - CondTools/SiPhase2Tracker/plugins/DTCCablingMapProducer.cc
 - CondTools/SiPhase2Tracker/plugins/DTCCablingMapTestProducer.cc
 - CondTools/SiPhase2Tracker/plugins/SiPhase2OuterTrackerLorentzAngleWriter.cc
 - CondTools/SiPixel/test/SiPixel2DTemplateDBObjectUploader.cc
 - CondTools/SiPixel/test/SiPixelGenErrorDBObjectUploader.cc
 - CondTools/SiPixel/test/SiPixelTemplateDBObjectUploader.cc
 - CondTools/SiStrip/plugins/SiStripApvGainRescaler.cc
 - CondTools/SiStrip/plugins/SiStripChannelGainFromDBMiscalibrator.cc
 - CondTools/SiStrip/plugins/SiStripNoisesFromDBMiscalibrator.cc
 - DQM/EcalMonitorDbModule/plugins/EcalDQMStatusWriter.cc
 - FWCore/ParameterSet/src/ParameterDescription.cc
 - Geometry/CaloEventSetup/test/CaloAlignmentRcdWrite.cc
 - Geometry/EcalAlgo/src/WriteESAlignments.cc
 - IOPool/Output/src/PoolOutputModule.cc
 - IOPool/Output/src/RootOutputFile.cc
 - JetMETCorrections/FFTJetModules/plugins/FFTJetCorrectorDBWriter.cc
 - JetMETCorrections/Modules/plugins/JetResolutionDBWriter.cc
 - L1Trigger/L1TMuonOverlap/plugins/L1TMuonOverlapParamsDBProducer.cc
 - L1TriggerConfig/Utilities/src/L1KeyListWriter.cc
 - L1TriggerConfig/Utilities/src/L1KeyWriter.cc
 - L1TriggerConfig/Utilities/src/L1MenuWriter.cc
 - L1TriggerConfig/Utilities/src/L1TCaloParamsUpdater.cc
 - L1TriggerConfig/Utilities/src/L1TCaloParamsWriter.cc
 - L1TriggerConfig/Utilities/src/L1TGlobalPrescalesVetosWriter.cc
 - L1TriggerConfig/Utilities/src/L1TMuonBarrelParamsWriter.cc
 - L1TriggerConfig/Utilities/src/L1TMuonEndCapForestWriter.cc
 - L1TriggerConfig/Utilities/src/L1TMuonEndCapParamsWriter.cc
 - L1TriggerConfig/Utilities/src/L1TMuonGlobalParamsWriter.cc
 - L1TriggerConfig/Utilities/src/L1TMuonOverlapParamsWriter.cc
 - RecoEgamma/EgammaTools/test/GBRWrapperMaker.cc
 - RecoMuon/GlobalTrackingTools/test/DYTTuner.cc
 - RecoParticleFlow/PFClusterTools/test/ProducePFCalibrationObject.cc
 - SimCalorimetry/EcalSelectiveReadoutProducers/src/EcalSRCondTools.cc
 - SimGeneral/MixingModule/plugins/Mixing2DB.cc

Will check out these packages, remove DB old method and see which fails to build.

**Comment by yuanchao** [comment]
By checking out the CMSSW_12_1_0_pre3, we have the latest DB code. I comment out the old writeOne API such that those not updated from the deprecated method will fail to build.

I grab the master CMSSW source tarball and copy the DB related packages over and compile. So far the following ones need to be updated:
 - Alignment/CommonAlignmentProducer
 - Alignment/LaserAlignment
 - Alignment/MuonAlignment
 - Alignment/OfflineValidation
 - Alignment/SurveyAnalysis
 - Alignment/TrackerAlignment
 - CalibMuon/DTCalibration
 - Calibration/TkAlCaRecoProducers

**Comment by tvami** [comment]
There is a partial fix in https://github.com/cms-sw/cmssw/pull/35616

**Comment by tvami** [comment]
First of the subsystem PR done in https://github.com/cms-sw/cmssw/pull/35999 (for SiStrips)

**Comment by tvami** [comment]
Hi @mmusich I found two more files for Strips
https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/src/SiStripGainsPCLHarvester.cc#L136
https://github.com/cms-sw/cmssw/blob/master/Alignment/CommonAlignmentAlgorithm/plugins/SiStripBackplaneCalibration.cc#L385
(although one might consider this to be an alignment file)

**Comment by mmusich** [comment]
https://github.com/cms-sw/cmssw/blob/master/Alignment/CommonAlignmentAlgorithm/plugins/SiStripBackplaneCalibration.cc#L385

Pertains to alignment

**Comment by mmusich** [comment]
While https://github.com/cms-sw/cmssw/blob/master/CalibTracker/SiStripChannelGain/src/SiStripGainsPCLHarvester.cc#L136 is already OK. It uses `std::unique_ptr`

**Comment by tvami** [comment]
I made a PR for the SiPixelCPE https://github.com/cms-sw/cmssw/pull/36027 I let the rest to @SanjanaSekhar

**Comment by tvami** [comment]
DropBox metadata (among other things) https://github.com/cms-sw/cmssw/pull/36028

**Comment by tvami** [comment]
Remaining SiPixel done in https://github.com/cms-sw/cmssw/pull/36040

**Comment by tvami** [comment]
ECAL is done in https://github.com/cms-sw/cmssw/pull/36062

**Comment by tvami** [comment]
Beamspot done in https://github.com/cms-sw/cmssw/pull/36077

**Comment by tvami** [comment]
TkAlignment done in https://github.com/cms-sw/cmssw/pull/36076

**Comment by tvami** [comment]
AlCa part done in https://github.com/cms-sw/cmssw/pull/36090
DB part done in https://github.com/cms-sw/cmssw/pull/36124

**Comment by tvami** [comment]
The removal of the old method happened in https://github.com/cms-sw/cmssw/pull/36490 , with this, this migration is completed!
